## Read Demographic dataset

In [1]:
import pandas as pd

# Read csv file save it in dataframe
demographic_covid_df = pd.read_csv("../../data/Demographic.csv")

# save dataframe to csv file and remove headers like "DP_04M"
demographic_covid_df.to_csv('Demographic.csv', header=False, index=False)

c:\users\codingtheories\pycharmprojects\csc-405-605_2020_assignment\venv\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (7,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,129,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,157,159,161,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,181,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,223,224,225,227,228,229,230,231,232,233,234,235,237,239,241,243,245,247,251,253,255,256,257,258,259,260,261,262,263,265,267,269,271,273,275,277,279,281,283,284,285,286,287,288,289,290,291,293,295,296,297,298,299,300,301,302,303,304,307,309,311,312,313,314,315,317,319,320,321,322,323,324,325,326,327,329,331,333,335,337,339,341,343,347,349,351,353,355,357) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

## Display Demographic Dataset

In [2]:
# Read csv file without header and save it in dataframe
demographic_df = pd.read_csv("Demographic.csv")
demographic_df.head(2)

,id,Geographic Area Name,Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Margin of Error!!RACE!!Total population,Percent Estimate!!RACE!!Total population,...,Margin of Error!!SEX AND AGE!!Total population!!65 years and over.1,Percent Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Percent Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Margin of Error!!SEX AND AGE!!Total population!!65 years and over!!Female,Percent Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female
0,0500000US01001,"Autauga County, Alabama",0.4,76.5,1.2,(X),(X),55200,*****,55200,...,75,8050,(X),3488,30,43.3,0.4,4562,65,56.7
1,0500000US01003,"Baldwin County, Alabama",0.1,86.6,0.3,(X),(X),208107,*****,208107,...,69,40665,(X),18870,40,46.4,0.1,21795,56,53.6

# Drop unwanted columns

In [3]:
# Remove columns which shows margin of errors, percent estimate and percent margin of error 

demographic_df = demographic_df[demographic_df.columns.drop(list(demographic_df.filter(regex='Margin')))]
demographic_df = demographic_df[demographic_df.columns.drop(list(demographic_df.filter(regex='Percent')))]

## Split id and Geographica Area Name

In [4]:
#Select column "id" from Demographic_df, and choose a substring of each value in the column which contains county FIPS,
#and append it to a list   

county_FIPS_list = []
for i in range(len(demographic_df["id"])):
    county_FIPS_list.append(demographic_df.loc[i,'id'][9:])
    
#Add the list as a new column to the Demographic_df     
demographic_df["countyFIPS"] = county_FIPS_list

#Convert the type of countyFIPS from string to int
demographic_df['countyFIPS'] = demographic_df['countyFIPS'].astype(int)

In [5]:
# Split geographical area name into county and state name

demographic_df[['County Name','State']] = demographic_df["Geographic Area Name"].str.split(",",expand=True)

In [6]:
demographic_df.head(2)

,id,Geographic Area Name,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,...,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,countyFIPS,County Name,State
0,0500000US01001,"Autauga County, Alabama",76.5,55200,54170,1030,54170,42437,10565,159,...,41831,20054,21777,92.1,8050,3488,4562,1001,Autauga County,Alabama
1,0500000US01003,"Baldwin County, Alabama",86.6,208107,204535,3572,204535,179526,19764,1522,...,162430,78104,84326,92.6,40665,18870,21795,1003,Baldwin County,Alabama

## In order to calcute correlation, read the confirmed cases and death datasets, and calculate the total number of confirmed cases and death for each county, merge them with Demographic dataset

In [7]:
# Read csv confirmed cases file and save it in a dataframe
confirmed_df = pd.read_csv("../../data/COVID-19 Dataset/confirmed.csv")

# Read csv death file and save it in a dataframe
death_df = pd.read_csv("../../data/COVID-19 Dataset/deaths.csv")

In [8]:
#sum up confirmed cases for each county
confirmed_df['Confirmed Total']= confirmed_df.iloc[:, 4:].sum(axis=1)

#sum up death for each county
death_df['death Total']= death_df.iloc[:, 4:].sum(axis=1)

In [9]:
death_df.head()

,countyFIPS,County Name,State,stateFIPS,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,9/6/20,9/7/20,9/8/20,9/9/20,9/10/20,9/11/20,9/12/20,9/13/20,9/14/20,death Total
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,24,24,24,24,24,24,24,24,24,1944
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,46,46,46,46,46,47,47,47,47,2577
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7,7,7,7,7,7,7,7,7,442
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,9,9,9,9,9,9,9,9,9,394

In [10]:
# define a new dataframe for confirmed cases which contains "countyFIPS", "County Name", "Confirmed Total"
modified_confirmed_df = confirmed_df[["countyFIPS", "County Name","State", "Confirmed Total"]]

# define a new dataframe for death cases which contains "countyFIPS", "County Name", "death Total"
modified_death_df = death_df[["countyFIPS", "County Name", "State","death Total"]]

In [11]:
#merge modified dataframes based on "countyFIPS", "County Name"
modified_confirmed_death_df = pd.merge(modified_confirmed_df,modified_death_df, on = ["countyFIPS", "County Name" ,"State"])

modified_confirmed_death_df.head()

   countyFIPS            County Name State  Confirmed Total  death Total
0           0  Statewide Unallocated    AL                0            0
1        1001         Autauga County    AL            99704         1944
2        1003         Baldwin County    AL           263916         2577
3        1005         Barbour County    AL            56401          442
4        1007            Bibb County    AL            36567          394

## Merge modified_confirmed_death_df with demographic dataset and then calculate correlation of each column with total confirmed and total death of each county

In [12]:
# merge demographic df with modified_confirmed_death
covid_demographic_ConfirmedDeath_df = pd.merge(modified_confirmed_death_df,demographic_df, on = ["countyFIPS"])

In [13]:
# define a list which contains column headers of covid_demographic_ConfirmedDeath_df
columns = covid_demographic_ConfirmedDeath_df.columns
columns_modified = columns[8:-2]

In [14]:
# calculate correlation for each column with total Confirmed cases and then append it to a list
correlation_confirmed = []
for i in range(len(columns_modified)-1):
    corr = covid_demographic_ConfirmedDeath_df["Confirmed Total"].corr(covid_demographic_ConfirmedDeath_df[columns_modified[i]])
    correlation_confirmed.append([columns_modified[i], corr])

#Sort the list 
correlation_confirmed = sorted(correlation_confirmed, key=lambda x: -x[1])
correlation_confirmed

[['Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female',
  0.9108461287302895],
 ['Estimate!!SEX AND AGE!!Total population!!Female', 0.9087851900430308],
 ['Estimate!!RACE!!Total population!!One race', 0.9082269481402986],
 ['Estimate!!RACE!!Total population!!One race.1', 0.9082269481402986],
 ['Estimate!!SEX AND AGE!!Total population!!21 years and over',
  0.9079007681947661],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over',
  0.9073745724714479],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over.1',
  0.9073745724714479],
 ['Estimate!!SEX AND AGE!!Total population!!16 years and over',
  0.9071724383485967],
 ['Estimate!!SEX AND AGE!!Total population!!45 to 54 years',
  0.907164595350125],
 ['Estimate!!RACE!!Total population', 0.905858378420767],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population',
  0.905858378420767],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population',
  0.905858378420767],
 ['Estimate!!SEX AND AGE!!Total population', 0.905858378420767],
 ['Estimate!!SEX AND AGE!!Total population!!55 to 59 years',
  0.9039310887663872],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male',
  0.9033563352657566],
 ['Estimate!!SEX AND AGE!!Total population!!35 to 44 years',
  0.9033477351538153],
 ['Estimate!!SEX AND AGE!!Total population!!60 to 64 years',
  0.9030032861142215],
 ['Estimate!!Total housing units', 0.9027739312054301],
 ['Estimate!!SEX AND AGE!!Total population!!Male', 0.9026129198429734],
 ['Estimate!!SEX AND AGE!!Total population!!75 to 84 years',
  0.902529082951892],
 ['Estimate!!SEX AND AGE!!Total population!!62 years and over',
  0.9023113023932183],
 ['Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female',
  0.9018571838521033],
 ['Estimate!!SEX AND AGE!!Total population!!65 years and over',
  0.9014870240382324],
 ['Estimate!!SEX AND AGE!!Total population!!65 years and over.1',
  0.9014870240382324],
 ['Estimate!!SEX AND AGE!!Total population!!25 to 34 years',
  0.9005976621140885],
 ['Estimate!!SEX AND AGE!!Total population!!Under 5 years', 0.899373605403205],
 ['Estimate!!SEX AND AGE!!Total population!!65 to 74 years',
  0.8989597393090779],
 ['Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population',
  0.8976053173470847],
 ['Estimate!!SEX AND AGE!!Total population!!85 years and over',
  0.8954231041678821],
 ['Estimate!!SEX AND AGE!!Total population!!Under 18 years',
  0.8942590337866383],
 ['Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male',
  0.8930939657553626],
 ['Estimate!!SEX AND AGE!!Total population!!15 to 19 years',
  0.8926692488879091],
 ['Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male',
  0.8925605697769697],
 ['Estimate!!SEX AND AGE!!Total population!!20 to 24 years',
  0.8920334471580185],
 ['Estimate!!SEX AND AGE!!Total population!!10 to 14 years',
  0.8906133826364585],
 ['Estimate!!SEX AND AGE!!Total population!!5 to 9 years', 0.8906043721390601],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race',
  0.8779116536625864],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino',
  0.8721568047174162],
 ['Estimate!!RACE!!Total population!!One race!!White', 0.8650876220421191],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino',
  0.8644778175357857],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!White',
  0.8644774668017977],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)',
  0.834318884857729],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American',
  0.8259229100932486],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone',
  0.8135559706442371],
 ['Estimate!!RACE!!Total population!!One race!!Black or African American',
  0.8109600997886643],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone',
  0.8009834589267036],
 ['Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American',
  0.7955301916595694],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone',
  0.791285619924901],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race',
  0.78960967507504],
 ['Estimate!!RACE!!Total population!!One race!!Some other race',
  0.7828095111836236],
 ['Estimate!!RACE!!Total population!!Two or more races', 0.768472867263648],
 ['Estimate!!RACE!!Total population!!Two or more races.1', 0.768472867263648],
 ['Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native',
  0.7653944735856689],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian',
  0.7507966514820678],
 ['Estimate!!RACE!!Total population!!One race!!Asian', 0.7208349600484493],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone',
  0.7205239362304566],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian',
  0.7180169411935978],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races',
  0.7069708613255092],
 ['Estimate!!RACE!!Total population!!Two or more races!!White and Asian',
  0.6911926306956557],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Chinese',
  0.688174918616892],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican',
  0.6877581734699854],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races',
  0.6877548137644026],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican',
  0.6687547909965731],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian',
  0.6652171862222875],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Korean',
  0.6609513021966981],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native',
  0.6535861537642434],
 ['Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native',
  0.6098325665765625],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Filipino',
  0.5963334558189324],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native',
  0.48297019853684003],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
  0.4662902345892358],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese',
  0.4329496284302003],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Japanese',
  0.4006743257144447],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
  0.37460484628739926],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban',
  0.34689432553883187],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone',
  0.2880102932379766],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
  0.24656546729013115],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone',
  0.23155787661688113],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
  0.23026021871279637],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander',
  0.2222235565572747],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
  0.16793808183292416],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
  0.10757869373413356],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
  0.10379966459834028],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
  0.05878472881242578],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
  0.05024911328847432],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)',
  -0.08140882748807371],
 ['Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)',
  -0.08308550822403458],
 ['Estimate!!SEX AND AGE!!Total population!!Median age (years)',
  -0.14766719716808605]]

In [15]:
# calculate correlation for each column with total death and then append it to a list
correlation_death = []
for i in range(len(columns_modified)-1):
    corr = covid_demographic_ConfirmedDeath_df["death Total"].corr(covid_demographic_ConfirmedDeath_df[columns_modified[i]])
    correlation_death.append([columns_modified[i], corr])
    
#Sort the list 
correlation_death = sorted(correlation_death, key=lambda x: x[1])
correlation_death

[['Estimate!!SEX AND AGE!!Total population!!Median age (years)',
  -0.08968007482403277],
 ['Estimate!!SEX AND AGE!!Total population!!Sex ratio (males per 100 females)',
  -0.0774028003136826],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)',
  -0.07594653514544944],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Sioux tribal grouping',
  0.022017586272392167],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Navajo tribal grouping',
  0.04734924062326771],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Chippewa tribal grouping',
  0.051070528542101264],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Native Hawaiian',
  0.05266740470253395],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native!!Cherokee tribal grouping',
  0.09416993144947156],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Native Hawaiian and Other Pacific Islander alone',
  0.10969116983753842],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Other Pacific Islander',
  0.11142879565822966],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Native Hawaiian and Other Pacific Islander',
  0.11952610776178478],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander',
  0.12101305525735583],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Cuban',
  0.13701022117221948],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!American Indian and Alaska Native alone',
  0.1588619138475459],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Samoan',
  0.18096564029634943],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Vietnamese',
  0.21758739116703316],
 ['Estimate!!RACE!!Total population!!One race!!Native Hawaiian and Other Pacific Islander!!Guamanian or Chamorro',
  0.2312922828016759],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Japanese',
  0.24365064528275934],
 ['Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native',
  0.28197594644907065],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Mexican',
  0.34552407576765015],
 ['Estimate!!RACE!!Total population!!Two or more races!!White and American Indian and Alaska Native',
  0.34853494521345],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Filipino',
  0.35451128737952103],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!American Indian and Alaska Native',
  0.4023813908495115],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races excluding Some other race, and Three or more races',
  0.4611024923475333],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Korean',
  0.46610243167486803],
 ['Estimate!!RACE!!Total population!!Two or more races!!White and Asian',
  0.46864530923884473],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races',
  0.48320258639547853],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)',
  0.5047077279189747],
 ['Estimate!!RACE!!Total population!!Two or more races', 0.524166313986753],
 ['Estimate!!RACE!!Total population!!Two or more races.1', 0.524166313986753],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Asian',
  0.5430846799431069],
 ['Estimate!!RACE!!Total population!!One race!!Some other race',
  0.5459266628300186],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Some other race',
  0.5512161391234256],
 ['Estimate!!RACE!!Total population!!One race!!Asian', 0.5525694246970198],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Asian alone',
  0.5533003501107461],
 ['Estimate!!RACE!!Total population!!Two or more races!!Black or African American and American Indian and Alaska Native',
  0.5699221497469074],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!White',
  0.5706068484748121],
 ['Estimate!!RACE!!Total population!!One race!!White', 0.5708675175119634],
 ['Estimate!!RACE!!Total population!!Two or more races!!White and Black or African American',
  0.5742851026715916],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!White alone',
  0.574822959869561],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Asian Indian',
  0.5864772407604838],
 ['Estimate!!SEX AND AGE!!Total population!!10 to 14 years',
  0.6050720119551223],
 ['Estimate!!SEX AND AGE!!Total population!!15 to 19 years',
  0.6061122396878934],
 ['Estimate!!SEX AND AGE!!Total population!!5 to 9 years', 0.6079839423229982],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Other Asian',
  0.6088804575119703],
 ['Estimate!!SEX AND AGE!!Total population!!Under 18 years',
  0.6133782573234232],
 ['Estimate!!SEX AND AGE!!Total population!!20 to 24 years',
  0.6167883334387364],
 ['Estimate!!RACE!!Total population!!One race!!Asian!!Chinese',
  0.6199588131390827],
 ['Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Male',
  0.6273984134647683],
 ['Estimate!!SEX AND AGE!!Total population!!Under 5 years',
  0.6287957161079833],
 ['Estimate!!SEX AND AGE!!Total population!!Male', 0.629550908714696],
 ['Estimate!!SEX AND AGE!!Total population!!35 to 44 years',
  0.6310480541551865],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male',
  0.6333272522804105],
 ['Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male',
  0.6359862028474217],
 ['Estimate!!RACE!!Total population', 0.6364697149956491],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population',
  0.6364697149956491],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population',
  0.6364697149956491],
 ['Estimate!!SEX AND AGE!!Total population', 0.6364697149956491],
 ['Estimate!!SEX AND AGE!!Total population!!45 to 54 years',
  0.6369946910208876],
 ['Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population',
  0.6370969816622387],
 ['Estimate!!RACE!!Total population!!One race', 0.6387872242016643],
 ['Estimate!!RACE!!Total population!!One race.1', 0.6387872242016643],
 ['Estimate!!SEX AND AGE!!Total population!!16 years and over',
  0.6410475165214223],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over',
  0.6420109495250582],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over.1',
  0.6420109495250582],
 ['Estimate!!SEX AND AGE!!Total population!!25 to 34 years',
  0.6425262806060309],
 ['Estimate!!SEX AND AGE!!Total population!!Female', 0.6430024931716408],
 ['Estimate!!SEX AND AGE!!Total population!!65 to 74 years',
  0.6437633598489996],
 ['Estimate!!SEX AND AGE!!Total population!!21 years and over',
  0.6438006111304829],
 ['Estimate!!SEX AND AGE!!Total population!!55 to 59 years',
  0.6441428038581263],
 ['Estimate!!CITIZEN, VOTING AGE POPULATION!!Citizen, 18 and over population!!Female',
  0.6457962575964038],
 ['Estimate!!SEX AND AGE!!Total population!!60 to 64 years',
  0.6479313891565984],
 ['Estimate!!Total housing units', 0.6480457143441317],
 ['Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female',
  0.6499742420078021],
 ['Estimate!!SEX AND AGE!!Total population!!62 years and over',
  0.6507390377809744],
 ['Estimate!!SEX AND AGE!!Total population!!65 years and over',
  0.6512673067538534],
 ['Estimate!!SEX AND AGE!!Total population!!65 years and over.1',
  0.6512673067538534],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino',
  0.6529825576766969],
 ['Estimate!!SEX AND AGE!!Total population!!75 to 84 years',
  0.6545394111635743],
 ['Estimate!!SEX AND AGE!!Total population!!85 years and over',
  0.6653694130574185],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Black or African American alone',
  0.6684357701372731],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Other Hispanic or Latino',
  0.6689532037879073],
 ['Estimate!!RACE!!Total population!!One race!!Black or African American',
  0.6835409467633052],
 ['Estimate!!Race alone or in combination with one or more other races!!Total population!!Black or African American',
  0.6898914139035238],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Hispanic or Latino (of any race)!!Puerto Rican',
  0.7326958901066524],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Two or more races!!Two races including Some other race',
  0.7555814930287758],
 ['Estimate!!HISPANIC OR LATINO AND RACE!!Total population!!Not Hispanic or Latino!!Some other race alone',
  0.7814218482344845]]

In [16]:
# sum up "under 5" and "5 to 9"
demographic_df["Estimate!!SEX AND AGE!!Total population!!Under 10 years"]= demographic_df.iloc[:, 64:66].sum(axis=1)

# sum up "10 to 14" and "15 to 19"
demographic_df["Estimate!!SEX AND AGE!!Total population!!10 to 19 years"] = demographic_df.iloc[:, 66:68].sum(axis=1)

# sum up "20 to 24" and "25 to 34"
demographic_df["Estimate!!SEX AND AGE!!Total population!!20 to 34 years"] = demographic_df.iloc[:, 68:70].sum(axis=1)

# sum up "55 to 59" and "60 to 64"
demographic_df["Estimate!!SEX AND AGE!!Total population!!55 to 64 years"] = demographic_df.iloc[:, 72:74].sum(axis=1)

## Choose important columns based on correlation values and define a new dataframe

In [17]:
demographic_df

,id,Geographic Area Name,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Sex ratio (males per 100 females),Estimate!!RACE!!Total population,Estimate!!RACE!!Total population!!One race,Estimate!!RACE!!Total population!!Two or more races,Estimate!!RACE!!Total population!!One race.1,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!RACE!!Total population!!One race!!American Indian and Alaska Native,...,Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,countyFIPS,County Name,State,Estimate!!SEX AND AGE!!Total population!!Under 10 years,Estimate!!SEX AND AGE!!Total population!!10 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 34 years,Estimate!!SEX AND AGE!!Total population!!55 to 64 years
0,0500000US01001,"Autauga County, Alabama",76.5,55200,54170,1030,54170,42437,10565,159,...,8050,3488,4562,1001,Autauga County,Alabama,7272,7425,10401,6825
1,0500000US01003,"Baldwin County, Alabama",86.6,208107,204535,3572,204535,179526,19764,1522,...,40665,18870,21795,1003,Baldwin County,Alabama,23298,27030,34116,29291
2,0500000US01005,"Barbour County, Alabama",76.2,25782,25429,353,25429,12216,12266,72,...,4634,2004,2630,1005,Barbour County,Alabama,2840,3111,5333,3308
3,0500000US01007,"Bibb County, Alabama",80.5,22527,22340,187,22340,17268,5018,8,...,3661,1633,2028,1007,Bibb County,Alabama,2453,2803,4566,2710
4,0500000US01009,"Blount County, Alabama",79.7,57645,56710,935,56710,55054,862,141,...,10233,4540,5693,1009,Blount County,Alabama,7117,7712,9975,7508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,0500000US72145,"Vega Baja Municipio, Puerto Rico",80.5,53371,52786,585,52786,45626,2725,68,...,9963,4442,5521,72145,Vega Baja Municipio,Puerto Rico,5148,7310,10382,6847
3216,0500000US72147,"Vieques Municipio, Puerto Rico",87.1,8771,8664,107,8664,5296,856,7,...,1826,850,976,72147,Vieques Municipio,Puerto Rico,1032,912,1572,1299
3217,0500000US72149,"Villalba Municipio, Puerto Rico",81.7,22993,16392,6601,16392,12293,647,0,...,3647,1640,2007,72149,Villalba Municipio,Puerto Rico,2599,3346,4557,3159
3218,0500000US72151,"Yabucoa Municipio, Puerto Rico",85.2,34149,33777,372,33777,10487,22748,39,...,6340,2916,3424,72151,Yabucoa Municipio,Puerto Rico,3564,4298,6297,4822
3219,0500000US72153,"Yauco Municipio, Puerto Rico",77.8,36439,35925,514,35925,28189,1300,152,...,7393,3235,4158,72153,Yauco Municipio,Puerto Rico,3655,4518,6433,5096

In [18]:
demographic_df_final = demographic_df[["countyFIPS", "County Name", "State", "Estimate!!SEX AND AGE!!Total population!!Under 10 years",
                                     "Estimate!!SEX AND AGE!!Total population!!10 to 19 years", "Estimate!!SEX AND AGE!!Total population!!20 to 34 years",
                                     "Estimate!!SEX AND AGE!!Total population!!35 to 44 years", "Estimate!!SEX AND AGE!!Total population!!45 to 54 years",
                                     "Estimate!!SEX AND AGE!!Total population!!55 to 64 years", "Estimate!!SEX AND AGE!!Total population!!65 to 74 years",
                                     "Estimate!!SEX AND AGE!!Total population!!75 to 84 years", "Estimate!!SEX AND AGE!!Total population!!85 years and over",
                                     "Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female", "Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male",
                                     "Estimate!!SEX AND AGE!!Total population!!Female","Estimate!!SEX AND AGE!!Total population!!Male",
                                      "Estimate!!RACE!!Total population!!One race!!White","Estimate!!RACE!!Total population!!One race!!Black or African American",
                                     "Estimate!!HISPANIC OR LATINO AND RACE!!Total population", "Estimate!!RACE!!Total population!!One race!!Asian"]]

In [19]:
demographic_df_final

,countyFIPS,County Name,State,Estimate!!SEX AND AGE!!Total population!!Under 10 years,Estimate!!SEX AND AGE!!Total population!!10 to 19 years,Estimate!!SEX AND AGE!!Total population!!20 to 34 years,Estimate!!SEX AND AGE!!Total population!!35 to 44 years,Estimate!!SEX AND AGE!!Total population!!45 to 54 years,Estimate!!SEX AND AGE!!Total population!!55 to 64 years,Estimate!!SEX AND AGE!!Total population!!65 to 74 years,Estimate!!SEX AND AGE!!Total population!!75 to 84 years,Estimate!!SEX AND AGE!!Total population!!85 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!Female,Estimate!!SEX AND AGE!!Total population!!Male,Estimate!!RACE!!Total population!!One race!!White,Estimate!!RACE!!Total population!!One race!!Black or African American,Estimate!!HISPANIC OR LATINO AND RACE!!Total population,Estimate!!RACE!!Total population!!One race!!Asian
0,1001,Autauga County,Alabama,7272,7425,10401,7374,7853,6825,4711,2524,815,4562,3488,28326,26874,42437,10565,55200,568
1,1003,Baldwin County,Alabama,23298,27030,34116,25377,28330,29291,24551,12165,3949,21795,18870,106919,101188,179526,19764,208107,1680
2,1005,Barbour County,Alabama,2840,3111,5333,3104,3452,3308,2820,1392,422,2630,2004,12085,13697,12216,12266,25782,96
3,1007,Bibb County,Alabama,2453,2803,4566,2895,3439,2710,2122,1112,427,2028,1633,10375,12152,17268,5018,22527,37
4,1009,Blount County,Alabama,7117,7712,9975,7153,7947,7508,6132,3235,866,5693,4540,29211,28434,55054,862,57645,198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Vega Baja Municipio,Puerto Rico,5148,7310,10382,6629,7092,6847,5652,2882,1429,5521,4442,27791,25580,45626,2725,53371,0
3216,72147,Vieques Municipio,Puerto Rico,1032,912,1572,1053,1077,1299,1038,504,284,976,850,4439,4332,5296,856,8771,156
3217,72149,Villalba Municipio,Puerto Rico,2599,3346,4557,2641,3044,3159,2262,1145,240,2007,1640,11824,11169,12293,647,22993,0
3218,72151,Yabucoa Municipio,Puerto Rico,3564,4298,6297,4183,4645,4822,3809,1699,832,3424,2916,17608,16541,10487,22748,34149,12
3219,72153,Yauco Municipio,Puerto Rico,3655,4518,6433,4455,4889,5096,4267,2212,914,4158,3235,18964,17475,28189,1300,36439,5

## Read the main covid dataset and merge it with demographic_df_final

In [20]:
#read the covid dataset
covid_df = pd.read_csv("../../data/output/covid.csv")
# del covid_df['Unnamed: 0']
type(covid_df["countyFIPS"][1])

numpy.int64

In [21]:
#merge covid_df with demographic_df_final 
covid_demoghraphic_df = pd.merge(covid_df,modified_death_df, on = ["countyFIPS"], how = "left")
covid_demoghraphic_df

,Unnamed: 0,countyFIPS,County Name_x,State_x,population,County Name_x,stateFIPS,1/22/20_x,1/23/20_x,1/24/20_x,...,9/8/20_y,9/9/20_y,9/10/20_y,9/11/20_y,9/12/20_y,9/13/20_y,9/14/20_y,County Name_y,State_y,death Total
0,0,0,Statewide Unallocated,AL,0,Statewide Unallocated,1,0,0,0,...,0,0,0,0,0,0,0,Statewide Unallocated,AL,0
1,0,0,Statewide Unallocated,AL,0,Statewide Unallocated,1,0,0,0,...,0,0,0,0,0,0,0,Statewide Unallocated,AK,45
2,0,0,Statewide Unallocated,AL,0,Statewide Unallocated,1,0,0,0,...,0,0,0,0,0,0,0,Statewide Unallocated,AZ,80
3,0,0,Statewide Unallocated,AL,0,Statewide Unallocated,1,0,0,0,...,0,0,0,0,0,0,0,Statewide Unallocated,AR,11
4,0,0,Statewide Unallocated,AL,0,Statewide Unallocated,1,0,0,0,...,0,0,0,0,0,0,0,Statewide Unallocated,CA,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5689,3190,56037,Sweetwater County,WY,42343,Sweetwater County,56,0,0,0,...,2,2,2,2,2,2,2,Sweetwater County,WY,124
5690,3191,56039,Teton County,WY,23464,Teton County,56,0,0,0,...,1,1,1,1,1,1,1,Teton County,WY,146
5691,3192,56041,Uinta County,WY,20226,Uinta County,56,0,0,0,...,2,2,2,2,2,2,2,Uinta County,WY,48
5692,3193,56043,Washakie County,WY,7805,Washakie County,56,0,0,0,...,6,6,6,6,6,6,6,Washakie County,WY,530
5693,3194,56045,Weston County,WY,6927,Weston County,56,0,0,0,...,0,0,0,0,0,0,0,Weston County,WY,0